# Generated by Django 3.2.5 on 2023-08-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
