# Generated by Django 4.2.4 on 2023-08-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_alter_transfer_amount_alter_transfer_transfer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
