# Generated by Django 4.2.4 on 2023-09-03 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfer', '0003_alter_transfer_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='destiny_account',
        ),
        migrations.AddField(
            model_name='transfer',
            name='email_destiny',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
